### ISSUE TITLE
Ativação/Desativação de ONGs/Campanhas/Eventos

### ISSUE THREAD

**Issue by LucJosin** [apoio-solidario/apoio-solidario-back-end#12]
Adicionar a opção de ativar/desativar ONGs/Campanhas/Eventos sem a necessidade de excluir as informações do banco de dados

**Comment by Joseulisses065** [comment]
**Descrição**
- Inserção do campo status nas tabelas:
    - Ong
    - Campanha
    - Evento
-  Criação do endpoint para atualizar o status nas tabelas:
    - Ong
    - Campanha
    - Evento

**Issues**
- Closes https://github.com/apoio-solidario/apoio-solidario-back-end/issues/12
