### ISSUE TITLE
[Proposta] Validar nome da ONG antes de salvar

### ISSUE THREAD

**Issue by LucJosin** [apoio-solidario/apoio-solidario-back-end#14]
A ideia é utilizar o nome da ong como id para a url do frontend

```json
{
  "id": 1,
  "name": "Associação de Pais e Amigos dos Excepcionais",
}
```

No frontend a url seria definida como:

`https://apoiosolidario.org/ongs/associacao-de-pais-e-amigos-dos-excepcionais/`

Para isso o **nome precisaria ser único**.

Outra solução é usar UUID ou ULID:

- UUID: `https://apoiosolidario.org/ongs/421da1e6-3748-47b8-a4ad-6b2b1b99d61d/`
- ULID: `https://apoiosolidario.org/ongs/01JCHKQS0MY6X70BZ9CW1K032A/`

cc: @Joseulisses065

**Comment by Joseulisses065** [comment]
**Descrição**
- Alteração na tabela ong para o campo name ser único.

**Issues**
- Closes https://github.com/apoio-solidario/apoio-solidario-back-end/issues/20
