### ISSUE TITLE
Atualizar estrutura das imagens

### ISSUE THREAD

**Issue by LucJosin** [apoio-solidario/apoio-solidario-back-end#15]
### Descrição

Atualizar tabela de imagens para ser mais genérica.

```sql

CREATE TABLE images (
  id INT AUTO_INCREMENT PRIMARY KEY,
  -- entity_type ..., não é necessário
  entity_id INT,
  image_name VARCHAR(255),
  image_url VARCHAR(255),
  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
  FOREIGN KEY (entity_id) REFERENCES ongs(id)
);
```

No caso da image de perfil e banner do(a) ong/campanha/evento:

```sql
CREATE TABLE ongs ( -- ONG / Campanha / Evento
  id INT AUTO_INCREMENT PRIMARY KEY,
  -- ...
  image_profile VARCHAR(255),
  image_banner VARCHAR(255)
)
```

**Comment by Joseulisses065** [comment]
**Descrição**
- Atualizar tabela de imagens para ser mais genérica.
- Adicionar image de perfil e banner de:
    - ong
    - campanha
    - evento
- Atualizar o camel case das requisições/respostas para snake case.

**Issues**
- Closes https://github.com/apoio-solidario/apoio-solidario-back-end/issues/15
