### ISSUE TITLE
Adicionar "handler" em ongs/campanhas/eventos

### ISSUE THREAD

**Issue by LucJosin** [apoio-solidario/apoio-solidario-back-end#21]
### Descrição

Adicionar coluna de "handler" nas entidades ongs/campanhas/eventos, esse campo será utilizado para identificação no front.

> O campo deve ser **Unico** e **Obrigatório**, a validação e inserção será feita através do front-end.

Também seria bom adicionar um endpoint getByHandler

- GET /api/ongs/handler/{handler}
- GET /api/campaigns/handler/{handler}
- GET /api/events/handler/{handler}

**Comment by Joseulisses065** [comment]
**Descrição**
- Inserção do campo handler nas tabelas:
    - Ong
    - Campanha
    - Evento
-  Criação do endpoint para busca por handler:
    - Ong
    - Campanha
    - Evento

**Issues**
- Closes https://github.com/apoio-solidario/apoio-solidario-back-end/issues/21
