### ISSUE TITLE
Adiconar controle de imagem com Cloudinary

### ISSUE THREAD

**Issue by LucJosin** [apoio-solidario/apoio-solidario-back-end#9]
Adiconar controle de imagem com Firebase Storage

### Referências

- [Spring Boot - File Upload to Firebase (Google Cloud)](https://gist.github.com/m-cakir/05470e679b73e2036254cef949432fcc)
- [File uploading with Spring Boot & Firebase Cloud Storage](https://medium.com/@poojithairosha/image-uploading-with-spring-boot-firebase-cloud-storage-e5ef2fbf942d)

**Comment by Joseulisses065** [comment]
Devido a algumas alterações feitas no Firebase, optamos pela troca da plataforma pela Cloudinary.

### Referências

- [Set Up Cloudinary as a Media Service in Your Spring Boot Project, It’s Free!](https://junkevin.medium.com/set-up-cloudinary-as-a-media-service-in-your-spring-boot-project-its-free-a26542af4408)

**Comment by Joseulisses065** [comment]
Devido a algumas alterações feitas no Firebase, decidimos substituir a plataforma de armazenamento de imagens pela Cloudinary. Essa mudança foi realizada para otimizar o processo de upload e gerenciamento de mídias, oferecendo mais recursos e flexibilidade na manipulação das imagens.

**Referência**

- [Set Up Cloudinary as a Media Service in Your Spring Boot Project, It’s Free!](https://junkevin.medium.com/set-up-cloudinary-as-a-media-service-in-your-spring-boot-project-its-free-a26542af4408)

A implementação foi concluída com sucesso e os testes indicam que a integração com a Cloudinary está funcionando corretamente.  Podemos otimizar ainda mais o sistema, armazenando a public key diretamente no banco de dados, associada à entidade de imagem, para facilitar a recuperação e o gerenciamento das imagens.

**Issues**
- Closes https://github.com/apoio-solidario/apoio-solidario-back-end/issues/9
